name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies and Build Project
        working-directory: frontend-project  # Adjust this to your frontend directory name
        run: |
          npm install
          npm run build

      - name: Deploy to Firebase Hosting
        working-directory: frontend-project  # Adjust this to your frontend directory name
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JOB_MATCH_WEB_32DB5 }}'
          channelId: live
          projectId: job-match-web-32db5
